version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    networks:
      - example-network
    ports:
      - '5432:5432'

networks:
  example-network:

volumes:
    db_data: